/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sirajinhoapp_icecast_CCompiler */

#ifndef _Included_com_sirajinhoapp_icecast_CCompiler
#define _Included_com_sirajinhoapp_icecast_CCompiler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sirajinhoapp_icecast_CCompiler
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sirajinhoapp_icecast_CCompiler_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
