/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sirajinhoapp_wificodeeditor_MainActivity */

#ifndef _Included_com_sirajinhoapp_wificodeeditor_MainActivity
#define _Included_com_sirajinhoapp_wificodeeditor_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sirajinhoapp_wificodeeditor_MainActivity
 * Method:    wificompile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sirajinhoapp_wificodeeditor_MainActivity_wificompile
  (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
